MONGO_URI = "mongodb://admin:lyn050227@cluster0-shard-00-00.drkdrz.mongodb.net:27017,cluster0-shard-00-01.drkdrz.mongodb.net:27017,cluster0-shard-00-02.drkdrz.mongodb.net:27017/coupon_system?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin"
DB_NAME = "coupon_system"

