MONGO_URI = "mongodb://admin:lyn050227@ac-raicbr6-shard-00-00.drkdhrz.mongodb.net:27017,ac-raicbr6-shard-00-01.drkdhrz.mongodb.net:27017,ac-raicbr6-shard-00-02.drkdhrz.mongodb.net:27017/coupon_system?ssl=true&replicaSet=atlas-6yi953-shard-0&authSource=admin&appName=Cluster0"
DB_NAME = "coupon_system"

